#pragma once

// from glfw3.h
#define YG_MOUSE_BUTTON_1      0
#define YG_MOUSE_BUTTON_2      1
#define YG_MOUSE_BUTTON_3      2
#define YG_MOUSE_BUTTON_4      3
#define YG_MOUSE_BUTTON_5      4
#define YG_MOUSE_BUTTON_6      5
#define YG_MOUSE_BUTTON_7      6
#define YG_MOUSE_BUTTON_8      7
#define YG_MOUSE_BUTTON_LAST   YG_MOUSE_BUTTON_8
#define YG_MOUSE_BUTTON_LEFT   YG_MOUSE_BUTTON_1
#define YG_MOUSE_BUTTON_RIGHT  YG_MOUSE_BUTTON_2
#define YG_MOUSE_BUTTON_MIDDLE YG_MOUSE_BUTTON_3